app = "localmart-frontend"
primary_region = "ewr" # Change this to your preferred region

[build]
  dockerfile = "Dockerfile.prod"
  [build.args]
    NEXT_PUBLIC_API_URL = "https://localmart-backend.fly.dev"
    NEXT_PUBLIC_POCKETBASE_URL = "https://localmart-pocketbase.fly.dev"
    NEXT_PUBLIC_SEARCH_URL = "https://localmart-search.fly.dev"
    NEXT_PUBLIC_MEILI_URL = "https://localmart-meilisearch.fly.dev"

[env]
  NODE_ENV = "production"
  PORT = "3000"
  NEXT_PUBLIC_API_URL = "https://localmart-backend.fly.dev"
  NEXT_PUBLIC_POCKETBASE_URL = "https://localmart-pocketbase.fly.dev"
  NEXT_PUBLIC_SEARCH_URL = "https://localmart-search.fly.dev"
  NEXT_PUBLIC_MEILI_URL = "https://localmart-meilisearch.fly.dev"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  max_machines_count = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 2048