services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_STRIPE_KEY=${NEXT_PUBLIC_STRIPE_KEY}
    depends_on:
      - backend

  backend:
    build:
      context: ./python-backend
      dockerfile: Dockerfile
    environment:
      - LOCALMART_UBER_DIRECT_CUSTOMER_ID=${LOCALMART_UBER_DIRECT_CUSTOMER_ID}
      - LOCALMART_UBER_DIRECT_CLIENT_ID=${LOCALMART_UBER_DIRECT_CLIENT_ID}
      - LOCALMART_UBER_DIRECT_CLIENT_SECRET=${LOCALMART_UBER_DIRECT_CLIENT_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    volumes:
      - ./python-backend:/app
    command: poetry run uvicorn localmart_backend.main:app --host 0.0.0.0 --reload
    depends_on:
      - pocketbase

  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: "listen --api-key ${STRIPE_SECRET_KEY} --forward-to backend:8000/api/v0/webhooks/stripe"
    environment:
      - STRIPE_API_KEY=${STRIPE_SECRET_KEY}
    depends_on:
      - backend

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    ports:
      - "8090:8090"
    volumes:
      - ./volumes/pocketbase_data:/pb_data
      - ./db/pb_migrations:/pb_migrations
    restart: unless-stopped

  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "7700:7700"
    volumes:
      - ./volumes/meilisearch_data:/data.ms
    environment:
      - MEILI_ENV=production
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-iyTjmntitsWVfallAEBbMyssNNRc-1TOFYW3wzI2r0}
    restart: unless-stopped

  search:
    build:
      context: ./search
      dockerfile: Dockerfile
    environment:
      - PORT=4100
      - PHX_HOST=localhost
      - MIX_ENV=prod
      - SECRET_KEY_BASE=1OhQxOL5gxafD09z/Eb0VNFw+qGInscrD2+oWgfXMsuYEafVFz/Jo+r+Vq4G3cOb
      - MEILI_ENDPOINT=http://meilisearch:7700
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-iyTjmntitsWVfallAEBbMyssNNRc-1TOFYW3wzI2r0}
    ports:
      - "4100:4100"
    depends_on:
      - meilisearch

volumes:
  pocketbase_data: