services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./python-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./python-backend:/app
    environment:
      - PYTHONPATH=/app
    command: poetry run uvicorn localmart_backend.main:app --host 0.0.0.0 --reload
    depends_on:
      - pocketbase

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    ports:
      - "8090:8090"
    volumes:
      - ./volumes/pocketbase_data:/pb_data
      - ./db/pb_migrations:/pb_migrations
    restart: unless-stopped

  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "7700:7700"
    volumes:
      - ./volumes/meilisearch_data:/data.ms
    restart: unless-stopped

  search:
    build:
      context: ./search
      dockerfile: Dockerfile
    environment:
      - PORT=4100
      - PHX_HOST=localhost
      - MIX_ENV=prod
      - SECRET_KEY_BASE=1OhQxOL5gxafD09z/Eb0VNFw+qGInscrD2+oWgfXMsuYEafVFz/Jo+r+Vq4G3cOb
      - MEILI_HOST=http://meilisearch:7700
    ports:
      - "4100:4100"
    depends_on:
      - meilisearch

volumes:
  pocketbase_data: 
