app = "localmart-search-prod"
primary_region = "ewr"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "4100"
  PHX_HOST = "localmart-search-prod.fly.dev"
  MIX_ENV = "prod"
  MEILI_HOST = "https://localmart-meilisearch-prod.fly.dev"
  MEILI_ENDPOINT = "https://localmart-meilisearch-prod.fly.dev"

[http_service]
  internal_port = 4100
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  max_machines_count = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024 