app = "localmart-meilisearch"
primary_region = "ewr"

[build]
  image = "getmeili/meilisearch:latest"

[env]
  MEILI_ENV = "production"
  MEILI_NO_ANALYTICS = "true"

[http_service]
  internal_port = 7700
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  max_machines_count = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "meili_data"
  destination = "/data.ms" 